"""create user table

Revision ID: 0be118b71755
Revises: 
Create Date: 2025-08-03 12:36:08.015371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0be118b71755'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('username'), table_name='users')
    op.drop_table('users')
    op.drop_table('vehicle_aggregated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_aggregated',
    sa.Column('ds', mysql.DATETIME(), nullable=False),
    sa.Column('y', mysql.INTEGER(), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.ENUM('ADMIN', 'CITY_ENGINEER', 'TRAFFIC_ENFORCER'), nullable=False),
    sa.Column('complete_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('complete_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_attempts', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('banned_until', mysql.DATETIME(), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
